services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
    ports:
      - 8211:8211/udp
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
      - 8212:8212/tcp  # Port for REST API if REST_API_ENABLED: true
      - 25575:25575
    environment:
      - TZ=Asia/Seoul
      - PLAYERS=16
      - PORT=8211
      - PUID=1001
      - PGID=1002
      - MULTITHREADING=true
      - COMMUNITY=false
      - PUBLIC_IP=
      - PUBLIC_PORT=8211
      - SERVER_NAME=서버이름
      - SERVER_DESCRIPTION=서버설명
      - SERVER_PASSWORD=worldofpals
      - ADMIN_PASSWORD=adminPasswordHere
      - UPDATE_ON_BOOT=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - QUERY_PORT=27015
      - BACKUP_ENABLED=true
      - DELETE_OLD_BACKUPS=true
      - OLD_BACKUP_DAYS=3
      - BACKUP_CRON_EXPRESSION=0 0 * * *
      - AUTO_UPDATE_ENABLED=false
      - AUTO_UPDATE_CRON_EXPRESSION=0 * * * *
      - AUTO_UPDATE_WARN_MINUTES=30
      - AUTO_REBOOT_ENABLED=false
      - AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE=false
      - AUTO_REBOOT_WARN_MINUTES=5
      - AUTO_REBOOT_CRON_EXPRESSION=0 0 * * *
      - AUTO_PAUSE_ENABLED=false
      - AUTO_PAUSE_TIMEOUT_EST=180
      - AUTO_PAUSE_LOG=true
      - AUTO_PAUSE_DEBUG=false
      - ENABLE_PLAYER_LOGGING=false
      - PLAYER_LOGGING_POLL_PERIOD=5
    volumes:
      - ./palworld:/palworld/
